version: '3.8'

services:
  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend/:/usr/src/frontend/
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8081"
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - "8081:8081"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: mysql:8.0.30-debian
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=test_password
      - MYSQL_USER=test_user
      - MYSQL_DATABASE=test_db
    restart: always

volumes:
    mysql_data:
