# Generated by Django 3.2 on 2022-09-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(editable=False, unique=True)),
                ('fullname', models.CharField(max_length=50)),
                ('issued_at', models.DateField()),
                ('expires_at', models.DateField()),
            ],
            options={
                'verbose_name': 'Identity',
                'verbose_name_plural': 'Identities',
                'db_table': 'identities',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('flags', models.SmallIntegerField()),
                ('verdict_type', models.SmallIntegerField()),
                ('verdict_result', models.SmallIntegerField()),
                ('verdict_name', models.CharField(max_length=10)),
                ('verdict_value', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
                'db_table': 'scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
