# Generated by Django 3.2 on 2022-09-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan_identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
