# Generated by Django 4.1 on 2022-09-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan_identity', '0002_rename_identity_id_scan_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='issued_at',
            field=models.DateField(null=True),
        ),
    ]
