# Generated by Django 4.1 on 2022-09-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan_identity', '0003_alter_identity_issued_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='expires_at',
            field=models.DateField(null=True),
        ),
    ]
