# Generated by Django 4.1 on 2022-09-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan_identity', '0004_alter_identity_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ['id'], 'verbose_name': 'Scan', 'verbose_name_plural': 'Scans'},
        ),
        migrations.RemoveField(
            model_name='scan',
            name='created_at',
        ),
    ]
