# Generated by Django 4.1 on 2022-10-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan_identity', '0005_alter_scan_options_remove_scan_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='verdict_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='scan',
            name='verdict_value',
            field=models.CharField(max_length=20),
        ),
    ]
